ALTER TABLE BUSINESS_ATTRIBUTES DROP INDEX B_ATTRIBUTE;
ALTER TABLE BUSINESS_CATEGORY DROP INDEX BUSINESS_CATEGORY_NAME;
ALTER TABLE REVIEWS DROP INDEX STARS;
ALTER TABLE REVIEWS DROP INDEX TOTAL_VOTES;
ALTER TABLE REVIEWS DROP INDEX DATEE;
ALTER TABLE YELP_USERS DROP INDEX YELPING_SINCE;
ALTER TABLE YELP_USERS DROP INDEX REVIEW_COUNT;
ALTER TABLE YELP_USERS DROP INDEX NO_OF_FRIENDS;
ALTER TABLE YELP_USERS DROP INDEX AVERAGE_STARS;
ALTER TABLE YELP_USERS DROP INDEX NO_OF_VOTES;

DROP TABLE REVIEWS;
DROP TABLE YELP_USERS;
DROP TABLE BUSINESS_CATEGORY;
DROP TABLE BUSINESS_HOURS;
DROP TABLE BUSINESS_ATTRIBUTES;
DROP TABLE BUSINESS_MAIN_CATEGORIES;
DROP TABLE BUSINESS;

